name: tyba_restaurant
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  logger: ^1.1.0
  json_annotation: ^4.5.0
  get_storage: ^2.0.3
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  sqflite: ^2.0.2+1
  flutter_rating_bar: ^4.0.1
  geolocator: ^8.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  hive_generator: ^1.1.3

flutter: 
  uses-material-design: true

